export const themes = [
    { "id": "vs", "name": "VS" },
    { "id": "vs-dark", "name": "VS Dark" },
    { "id": "hc-black", "name": "High Contrast (Dark)" },
    { "id": "active4d", "name": "Active4D" },
    { "id": "all-hallows-eve", "name": "All Hallows Eve" },
    { "id": "amy", "name": "Amy" },
    { "id": "birds-of-paradise", "name": "Birds of Paradise" },
    { "id": "blackboard", "name": "Blackboard" },
    { "id": "brilliance-black", "name": "Brilliance Black" },
    { "id": "brilliance-dull", "name": "Brilliance Dull" },
    { "id": "chrome-devtools", "name": "Chrome DevTools" },
    { "id": "clouds-midnight", "name": "Clouds Midnight" },
    { "id": "clouds", "name": "Clouds" },
    { "id": "cobalt", "name": "Cobalt" },
    { "id": "cobalt2", "name": "Cobalt2" },
    { "id": "dawn", "name": "Dawn" },
    { "id": "dracula", "name": "Dracula" },
    { "id": "dreamweaver", "name": "Dreamweaver" },
    { "id": "eiffel", "name": "Eiffel" },
    { "id": "espresso-libre", "name": "Espresso Libre" },
    { "id": "github-dark", "name": "GitHub Dark" },
    { "id": "github-light", "name": "GitHub Light" },
    { "id": "github", "name": "GitHub" },
    { "id": "idle", "name": "IDLE" },
    { "id": "katzenmilch", "name": "Katzenmilch" },
    { "id": "kuroir-theme", "name": "Kuroir Theme" },
    { "id": "lazy", "name": "LAZY" },
    { "id": "magicwb--amiga-", "name": "MagicWB (Amiga)" },
    { "id": "merbivore-soft", "name": "Merbivore Soft" },
    { "id": "merbivore", "name": "Merbivore" },
    { "id": "monokai-bright", "name": "Monokai Bright" },
    { "id": "monokai", "name": "Monokai" },
    { "id": "night-owl", "name": "Night Owl" },
    { "id": "nord", "name": "Nord" },
    { "id": "oceanic-next", "name": "Oceanic Next" },
    { "id": "pastels-on-dark", "name": "Pastels on Dark" },
    { "id": "slush-and-poppies", "name": "Slush and Poppies" },
    { "id": "solarized-dark", "name": "Solarized-dark" },
    { "id": "solarized-light", "name": "Solarized-light" },
    { "id": "spacecadet", "name": "SpaceCadet" },
    { "id": "sunburst", "name": "Sunburst" },
    { "id": "textmate--mac-classic-", "name": "Textmate (Mac Classic)" },
    { "id": "tomorrow-night-blue", "name": "Tomorrow-Night-Blue" },
    { "id": "tomorrow-night-bright", "name": "Tomorrow-Night-Bright" },
    { "id": "tomorrow-night-eighties", "name": "Tomorrow-Night-Eighties" },
    { "id": "tomorrow-night", "name": "Tomorrow-Night" },
    { "id": "tomorrow", "name": "Tomorrow" },
    { "id": "twilight", "name": "Twilight" },
    { "id": "upstream-sunburst", "name": "Upstream Sunburst" },
    { "id": "vibrant-ink", "name": "Vibrant Ink" },
    { "id": "xcode-default", "name": "Xcode_default" },
    { "id": "zenburnesque", "name": "Zenburnesque" },
    { "id": "iplastic", "name": "iPlastic" },
    { "id": "idlefingers", "name": "idleFingers" },
    { "id": "krtheme", "name": "krTheme" },
    { "id": "monoindustrial", "name": "monoindustrial" }
  ]

export const themeMap: Record<string, () => Promise<any>> = {
  "active4d": () => import("monaco-themes/themes/Active4D.json"),
  "all-hallows-eve": () => import("monaco-themes/themes/All Hallows Eve.json"),
  "amy": () => import("monaco-themes/themes/Amy.json"),
  "birds-of-paradise": () => import("monaco-themes/themes/Birds of Paradise.json"),
  "blackboard": () => import("monaco-themes/themes/Blackboard.json"),
  "brilliance-black": () => import("monaco-themes/themes/Brilliance Black.json"),
  "brilliance-dull": () => import("monaco-themes/themes/Brilliance Dull.json"),
  "chrome-devtools": () => import("monaco-themes/themes/Chrome DevTools.json"),
  "clouds-midnight": () => import("monaco-themes/themes/Clouds Midnight.json"),
  "clouds": () => import("monaco-themes/themes/Clouds.json"),
  "cobalt": () => import("monaco-themes/themes/Cobalt.json"),
  "cobalt2": () => import("monaco-themes/themes/Cobalt2.json"),
  "dawn": () => import("monaco-themes/themes/Dawn.json"),
  "dracula": () => import("monaco-themes/themes/Dracula.json"),
  "dreamweaver": () => import("monaco-themes/themes/Dreamweaver.json"),
  "eiffel": () => import("monaco-themes/themes/Eiffel.json"),
  "espresso-libre": () => import("monaco-themes/themes/Espresso Libre.json"),
  "github-dark": () => import("monaco-themes/themes/GitHub Dark.json"),
  "github-light": () => import("monaco-themes/themes/GitHub Light.json"),
  "github": () => import("monaco-themes/themes/GitHub.json"),
  "idle": () => import("monaco-themes/themes/IDLE.json"),
  "katzenmilch": () => import("monaco-themes/themes/Katzenmilch.json"),
  "kuroir-theme": () => import("monaco-themes/themes/Kuroir Theme.json"),
  "lazy": () => import("monaco-themes/themes/LAZY.json"),
  "magicwb--amiga-": () => import("monaco-themes/themes/MagicWB (Amiga).json"),
  "merbivore-soft": () => import("monaco-themes/themes/Merbivore Soft.json"),
  "merbivore": () => import("monaco-themes/themes/Merbivore.json"),
  "monokai-bright": () => import("monaco-themes/themes/Monokai Bright.json"),
  "monokai": () => import("monaco-themes/themes/Monokai.json"),
  "night-owl": () => import("monaco-themes/themes/Night Owl.json"),
  "nord": () => import("monaco-themes/themes/Nord.json"),
  "oceanic-next": () => import("monaco-themes/themes/Oceanic Next.json"),
  "pastels-on-dark": () => import("monaco-themes/themes/Pastels on Dark.json"),
  "slush-and-poppies": () => import("monaco-themes/themes/Slush and Poppies.json"),
  "solarized-dark": () => import("monaco-themes/themes/Solarized-dark.json"),
  "solarized-light": () => import("monaco-themes/themes/Solarized-light.json"),
  "spacecadet": () => import("monaco-themes/themes/SpaceCadet.json"),
  "sunburst": () => import("monaco-themes/themes/Sunburst.json"),
  "textmate--mac-classic-": () => import("monaco-themes/themes/Textmate (Mac Classic).json"),
  "tomorrow-night-blue": () => import("monaco-themes/themes/Tomorrow-Night-Blue.json"),
  "tomorrow-night-bright": () => import("monaco-themes/themes/Tomorrow-Night-Bright.json"),
  "tomorrow-night-eighties": () => import("monaco-themes/themes/Tomorrow-Night-Eighties.json"),
  "tomorrow-night": () => import("monaco-themes/themes/Tomorrow-Night.json"),
  "tomorrow": () => import("monaco-themes/themes/Tomorrow.json"),
  "twilight": () => import("monaco-themes/themes/Twilight.json"),
  "upstream-sunburst": () => import("monaco-themes/themes/Upstream Sunburst.json"),
  "vibrant-ink": () => import("monaco-themes/themes/Vibrant Ink.json"),
  "xcode-default": () => import("monaco-themes/themes/Xcode_default.json"),
  "zenburnesque": () => import("monaco-themes/themes/Zenburnesque.json"),
  "iplastic": () => import("monaco-themes/themes/iPlastic.json"),
  "idlefingers": () => import("monaco-themes/themes/idleFingers.json"),
  "krtheme": () => import("monaco-themes/themes/krTheme.json"),
  "monoindustrial": () => import("monaco-themes/themes/monoindustrial.json")
};

  